### PR TITLE
Add support to compile the project with CMake+MSVC on Windows

### PR DESCRIPTION
**Pull request by dacap**
This commit adds support to compile the project with MSVC using CMake. Anyway I'm not sure if you want to add CMake as your compiling system.

The program compiled correctly but it crashes after the execution, so I'll take a look tomorrow to know why it crashes.

### CODE REVIEW

**Comment by felipetavares** [comment]
Any reason for using cmake 3.0 instead of 2.8?

**Comment by dacap** [comment]
There is no reason, I think 2.8 will be just fine :+1: :smile:

**Comment by felipetavares** [comment]
Updated to use 2.8, as it's still pretty common. Also made some modifications to allow it to compile under my linux distro - I'm not sure if it was compiling on linux at all before.

**Comment by dacap** [comment]
I didn't try the Linux port, so all kind of needed changes seems ok :+1:

**Pull request merged**
